[package]
name = "rust-webserver"
version = "0.1.0"
authors = ["Colby Reinhart"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
